epochs: 10
resume: None
learning_rate: 0.001
weight_decay: 10e-6
inference_device: "cuda"

train:
  batch_size: 4
  num_workers: 4
  valid_size: 0.3
  train_path: "./2_data/train"

test:
  batch_size: 4
  num_workers: 4
  test_path: "./2_data/val"

model:
  base_model: "convnext_base"
