epochs: 10
resume: None
learning_rate: 2e-05
weight_decay: 10e-6
inference_device: "cuda"

train:
  batch_size: 16
  num_workers: 4
  valid_size: 0.3
  train_path: "./data/train"

test:
  batch_size: 16
  num_workers: 4
  test_path: "./data/val"

model:
  base_model: "resnet_50"
